@domain = http://localhost:3000
@Token = {{response.body.$.accessToken}}

###
# 회원가입
POST {{domain}}/user/signup
Content-Type: application/json

{
  "name": "test",
  "email": "test@test.com",
  "password": "1234",
  "phone": "010-0000-0000",
  "role": "admin", 
  "couponNames": ["register"]
}

###
# Redis 연결 체크
GET {{domain}}/auth

###
# 로그인
POST {{domain}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}   

###
# 가드 적용 유무
GET {{domain}}/coupon/cou

